name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@main
      - name: Use Node.js
        uses: actions/setup-node@main
        with:
          node-version: '16.x'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
